global using MediatR;
global using AutoMapper.QueryableExtensions;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using System.Data;
global using Microsoft.Extensions.Logging;
global using EcosferaBlazor.Auth.Domain.Entities;
global using EcosferaBlazor.Auth.Domain.Identity;
global using EcosferaBlazor.Auth.Application.Common.Models;
global using EcosferaBlazor.Auth.Application.Common.Interfaces;
global using EcosferaBlazor.Auth.Infrastructure.Extensions;
global using EcosferaBlazor.Auth.Application.Constants;
global using Microsoft.AspNetCore.Components;
global using Fluxor.Blazor.Web.Components;
global using MudBlazor;
global using Fluxor;
global using Severity = MudBlazor.Severity;
global using Color = MudBlazor.Color;